services:
  c:
    container_name: benchmark-c-gcc
    build: ./src/c
    command: sh -c "strace -c -o /traces/c-gcc-traces.txt ./c-gcc"
    volumes:
      - ./traces:/traces

  clojure:
    container_name: benchmark-clojure
    build: ./src/clojure
    command: sh -c "strace -c -o /traces/clojure-traces.txt clj clojure.clj"
    volumes:
      - ./traces:/traces

  cpp:
    container_name: benchmark-cpp-gcc
    build: ./src/cpp
    command: sh -c "strace -c -o /traces/cpp-gcc-traces.txt ./cpp-gcc"
    volumes:
      - ./traces:/traces

  csharp:
    container_name: benchmark-csharp
    build: ./src/csharp
    command: sh -c "strace -c -o /traces/csharp-traces.txt dotnet csharp.dll"
    volumes:
      - ./traces:/traces

  dart:
    container_name: benchmark-dart
    build: ./src/dart
    command: sh -c "strace -c -o /traces/dart-traces.txt ./dart"
    volumes:
      - ./traces:/traces

  elixir:
    container_name: benchmark-elixir
    build: ./src/elixir
    command: sh -c "strace -c -o /traces/elixir-traces.txt elixir -e "Elxir.hello""
    volumes:
      - ./traces:/traces

  erlang:
    container_name: benchmark-erlang
    build: ./src/erlang
    command: sh -c "strace -c -o /traces/erlang-traces.txt erl -noshell -eval "erlang.main" -s init stop"
    volumes:
      - ./traces:/traces

  go:
    container_name: benchmark-go
    build: ./src/go
    command: sh -c "strace -c -o /traces/go-traces.txt ./hello"
    volumes:
      - ./traces:/traces

  groovy:
    container_name: benchmark-groovy
    build: ./src/groovy
    command: sh -c "strace -c -o /traces/groovy-traces.txt groovy hello.groovy"
    volumes:
      - ./traces:/traces

  haskell:
    container_name: benchmark-haskell
    build: ./src/haskell
    command: sh -c "strace -c -o /traces/haskell-traces.txt ./haskell"
    volumes:
      - ./traces:/traces

  java:
    container_name: benchmark-java
    build: ./src/java
    command: sh -c "strace -c -o /traces/java-traces.txt java HelloWorld"
    volumes:
      - ./traces:/traces

  python:
    container_name: benchmark-cpython
    build: ./src/python
    command: sh -c "strace -c -o /traces/cpython-traces.txt python3 python.py"
    volumes:
      - ./traces:/traces
