services:
  c:
    container_name: benchmark-c-gcc
    build: ./src/c
    command: sh -c "strace -c -o /traces/c-gcc-traces.txt ./c-gcc"
    volumes:
      - ./traces:/traces

  clojure:
    container_name: benchmark-clojure
    build: ./src/clojure
    command: sh -c "strace -c -o /traces/clojure-traces.txt clj clojure.clj"
    volumes:
      - ./traces:/traces

  cpp:
    container_name: benchmark-cpp-gcc
    build: ./src/cpp
    command: sh -c "strace -c -o /traces/cpp-gcc-traces.txt ./cpp-gcc"
    volumes:
      - ./traces:/traces

  csharp:
    container_name: benchmark-csharp
    build: ./src/csharp
    command: sh -c "strace -c -o /traces/csharp-traces.txt dotnet csharp.dll"
    volumes:
      - ./traces:/traces

  dart:
    container_name: benchmark-dart
    build: ./src/dart
    command: sh -c "strace -c -o /traces/dart-traces.txt ./dart"
    volumes:
      - ./traces:/traces

  elixir:
    container_name: benchmark-elixir
    build: ./src/elixir
    command: sh -c "strace -c -o /traces/elixir-traces.txt elixir -e "Elxir.hello""
    volumes:
      - ./traces:/traces

  erlang:
    container_name: benchmark-erlang
    build: ./src/erlang
    command: sh -c "strace -c -o /traces/erlang-traces.txt erl -noshell -eval "erlang.main" -s init stop"
    volumes:
      - ./traces:/traces

  go:
    container_name: benchmark-go
    build: ./src/go
    command: sh -c "strace -c -o /traces/go-traces.txt ./hello"
    volumes:
      - ./traces:/traces

  groovy:
    container_name: benchmark-groovy
    build: ./src/groovy
    command: sh -c "strace -c -o /traces/groovy-traces.txt groovy hello.groovy"
    volumes:
      - ./traces:/traces

  haskell:
    container_name: benchmark-haskell
    build: ./src/haskell
    command: sh -c "strace -c -o /traces/haskell-traces.txt ./haskell"
    volumes:
      - ./traces:/traces

  java:
    container_name: benchmark-java
    build: ./src/java
    command: sh -c "strace -c -o /traces/java-traces.txt java HelloWorld"
    volumes:
      - ./traces:/traces

  node:
    container_name: benchmark-node
    build: ./src/js/node
    command: sh -c "strace -c -o /traces/node-traces.txt node node.js"
    volumes:
      - ./traces:/traces

  deno:
    container_name: benchmark-deno
    build: ./src/js/deno
    command: sh -c "strace -c -o /traces/deno-traces.txt deno run deno.ts"
    volumes:
      - ./traces:/traces

  bun:
    container_name: benchmark-bun
    build: ./src/js/bun
    command: sh -c "strace -c -o /traces/bun-traces.txt bun run bun.ts"
    volumes:
      - ./traces:/traces

  python:
    container_name: benchmark-cpython
    build: ./src/python
    command: sh -c "strace -c -o /traces/cpython-traces.txt python3 python.py"
    volumes:
      - ./traces:/traces

  julia:
    container_name: benchmark-julia
    build: ./src/julia
    command: sh -c "strace -c -o /traces/julia-traces.txt julia julia.jl"
    volumes:
      - ./traces:/traces

  kotlin:
    container_name: benchmark-kotlin
    build: ./src/kotlin
    command: sh -c "strace -c -o /traces/kotlin-traces.txt java -jar kotlin.jar"
    volumes:
      - ./traces:/traces

  lua:
    container_name: benchmark-lua
    build: ./src/lua
    command: sh -c "strace -c -o /traces/lua-traces.txt lua lua.lua"
    volumes:
      - ./traces:/traces

  perl:
    container_name: benchmark-perl
    build: ./src/perl
    command: sh -c "strace -c -o /traces/perl-traces.txt perl perl.pl"
    volumes:
      - ./traces:/traces

  php:
    container_name: benchmark-php
    build: ./src/php
    command: sh -c "strace -c -o /traces/php-traces.txt php php.php"
    volumes:
      - ./traces:/traces

  r:
    container_name: benchmark-r
    build: ./src/r
    command: sh -c "strace -c -o /traces/r-traces.txt Rscript r.r"
    volumes:
      - ./traces:/traces

  ruby:
    container_name: benchmark-ruby
    build: ./src/ruby
    command: sh -c "strace -c -o /traces/ruby-traces.txt ruby ruby.rb"
    volumes:
      - ./traces:/traces

  rust:
    container_name: benchmark-rust
    build: ./src/rust
    command: sh -c "strace -c -o /traces/rust-traces.txt ./rust"
    volumes:
      - ./traces:/traces

  scala:
    container_name: benchmark-scala
    build: ./src/scala
    command: sh -c "strace -c -o /traces/scala-traces.txt scala scala.scala"
    volumes:
      - ./traces:/traces

  swift:
    container_name: benchmark-swift
    build: ./src/swift
    command: sh -c "strace -c -o /traces/swift-traces.txt ./swift"
    volumes:
      - ./traces:/traces

  zig:
    container_name: benchmark-zig
    build: ./src/zig
    command: sh -c "strace -c -o /traces/zig-traces.txt ./zig"
    volumes:
      - ./traces:/traces
