services:
  c:
    container_name: benchmark-c-gcc
    build: ./src/c
    command: sh -c "strace -c -o /traces/c-gcc-traces.txt ./c-gcc"
    volumes:
      - ./traces:/traces

  cpp:
    container_name: benchmark-cpp-gcc
    build: ./src/cpp
    command: sh -c "strace -c -o /traces/cpp-gcc-traces.txt ./cpp-gcc"
    volumes:
      - ./traces:/traces

  python:
    container_name: benchmark-cpython
    build: ./src/python
    command: sh -c "strace -c -o /traces/cpython-traces.txt python3 python.py"
    volumes:
      - ./traces:/traces
