services:
  c:
    container_name: benchmark-c-gcc
    build: ./src/c
    command: sh -c "strace -c -o /traces/c-gcc-traces.txt ./c-gcc"
    volumes:
      - ./traces:/traces

  clojure:
    container_name: benchmark-clojure
    build: ./src/clojure
    command: sh -c "strace -c -o /traces/clojure-traces.txt clj clojure.clj"
    volumes:
      - ./traces:/traces

  cpp:
    container_name: benchmark-cpp-gcc
    build: ./src/cpp
    command: sh -c "strace -c -o /traces/cpp-gcc-traces.txt ./cpp-gcc"
    volumes:
      - ./traces:/traces

  csharp:
    container_name: benchmark-csharp
    build: ./src/csharp
    command: sh -c "strace -c -o /traces/csharp-traces.txt dotnet csharp.dll"
    volumes:
      - ./traces:/traces

  dart:
    container_name: benchmark-dart
    build: ./src/dart
    command: sh -c "strace -c -o /traces/dart-traces.txt ./dart"
    volumes:
      - ./traces:/traces

  python:
    container_name: benchmark-cpython
    build: ./src/python
    command: sh -c "strace -c -o /traces/cpython-traces.txt python3 python.py"
    volumes:
      - ./traces:/traces
